image:
  repository: slimboi/flask-kubernetes-pipeline
  tag: 82f1a10
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false