image:
  repository: thedevopsdude/complete-devops-project
  tag: 2ae72ee
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
serviceAccount:
  enabled: false
autoscaling:
  enabled: false